server:
  port: 12011

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://172.30.150.133:8761/eureka/
      #defaultZone:  http://eureka-hs.default.svc.cluster.local:8761/eureka/
      defaultZone:  http://172.30.150.60:60702/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  zipkin:
    enabled: false
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      percentage: 1.0
payment:
   sUrl: http://117.185.124.17:10100/AdvPayHttpService
   sPageURL:
#   sPayNotifyIntURL: http://112.17.9.86:10060/cartoon/order/payNoticeZF
   sPayNotifyIntURL: http://112.17.9.87:18080/cartoon/order/payNoticeZF
   sTimeOut: 1000
   sProxyServer: 172.30.150.166
   sProxyServerPort: 10050
   sKey: 30819f300d06092a864886f70d010101050003818d00308189028181008956ace11fe1a3a560f7d73ebe1a87f977fdaed759db0aed831e1869b6e8e2923157d8cd035f0be61f50ca5bf08b1a631bab40f3087590fa8d29e94209a21e5cb262b9c43fc6d2493b017618318a3f679816af61a9fb7fa6d0dcb149ff9b18af36367a1d24e154de6c4243d31411066d4c33ef0afd7658b52cf8df6b4942a0310203010001
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    