eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/

sleuth:
  sampler:
    percentage: 1.0